# Generated by Django 3.0.7 on 2020-06-22 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('last_updated', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'ingredient',
                'ordering': ['id'],
            },
        ),
    ]
