# Generated by Django 3.0.7 on 2020-06-23 18:28

from django.db import migrations

def create_dummy_tasks(apps, schema_editor):
    Ingredient = apps.get_model('api', 'Ingredient')

    Ingredient(name='Bread', description='white bread ew carbs').save()
    Ingredient(name='Apple', description='keeps the doctor away').save()
    Ingredient(name='Orange', description='too sweet, not real').save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_tasks),
    ]
